acilearning/prolude

prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/49989
=> Version Bump

Prolude.hs, Prolude/Monad.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/51115
=> Add Control.Monad to Prolude

Prolude/Foldable.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/51968
=> Add Data.Set to Prolude

Prolude.hs, Prolude/Csv.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/52460
=> Add Data.Csv

Prolude/Csv.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/52460
Whoops, hard to use functions ya can't access :sweat_smile:
=> Csv Exports

Prolude.hs, Prolude/ByteString.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/52930
=> Add Data.ByteString

Prolude.hs, Prolude/Prim.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/53236
=> add primitive types to Prolude.Prim

Prolude.hs, Prolude/Swagger.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/53932
=> Add Data.Swagger

Prolude/Core.hs, Prolude/Text.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/54050
=> Fix Prolude Issues

Prolude.hs, Prolude/Lens.hs, Prolude/Uuid.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/54633
=> Add Control.Lens

Prolude.hs, Prolude/Aeson.hs, Prolude/ByteString.hs, Prolude/Core.hs, Prolude/Csv.hs, Prolude/Exception.hs, Prolude/Foldable.hs, Prolude/Json.hs, Prolude/MongoDB.hs, Prolude/Swagger.hs, Prolude/Test.hs, Prolude/Text.hs, Prolude/Time.hs, Prolude/Uuid.hs
Story details: https://app.clubhouse.io/itprotv/story/55149
=> Better Prolude Documentation

Prolude.hs, Prolude/Servant.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/55876
=> Add Servant

Prolude/Maybe.hs
idea to add some useful functions for marshaling between `Either l` and `Maybe`
=> add note + hush

Prolude/Servant.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/56944
=> Prefer HttpSummary

Prolude.hs, Prolude/Aws.hs, Prolude/Servant.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/55877
=> Add Network.AWS

Prolude/Swagger.hs, prolude.cabal
Story details: https://app.clubhouse.io/itprotv/story/90480
---
=> Produce named schemas by default

Prolude/Core.hs, prolude.cabal
Silly mistake on my part 🤦 
---
=> Re-export Natural

.github/workflows/ci.yaml, Prolude.hs, Prolude/Aws.hs, Prolude/Core.hs, Prolude/Csv.hs, Prolude/Esqueleto.hs, Prolude/Exception.hs, Prolude/Lens.hs, Prolude/Maybe.hs, Prolude/Monad.hs, Prolude/MongoDB.hs, Prolude/Persist.hs, Prolude/Prim.hs, Prolude/Servant.hs, Prolude/Swagger.hs, Prolude/Test.hs, Prolude/Uri.hs, Prolude/Uuid.hs, prolude.cabal
=> Re-export HasCallStack

prolude.cabal
Story details: https://app.shortcut.com/itprotv/story/112729
---
=> Allow Servant 0.19

prolude.cabal
=> Allow aeson 2.1
